import Head from 'next/head';
import { Navbar } from '../components/navbar/navbar.component';
import { Footer } from '../components/footer/footer.component';
import { GalleryContent } from '../components/galleryContent/galleryContent.component';

export default function Home({ images }) {
    return (
        <>
            <Head>
                <title>Szmatki Kwiatki i Bukiety</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                    lang="pl"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <GalleryContent images={images} />
            <Footer />
        </>
    );
}

export async function getStaticProps() {
    const params = {
        expression: 'folder="sk_gallery"',
    };
    const paramString = Object.keys(params)
        .map((key) => `${key}=${encodeURIComponent(params[key])}`)
        .join('&');

    const results = await fetch(
        `https://api.cloudinary.com/v1_1/${process.env.CLOUDINARY_CLOUD_NAME}/resources/search?${paramString}`,
        {
            headers: {
                Authorization: `Basic ${Buffer.from(
                    process.env.CLOUDINARY_API_KEY +
                        ':' +
                        process.env.CLOUDINARY_API_SECRET
                ).toString('base64')}`,
            },
        }
    ).then((r) => r.json());

    const { resources } = results;

    const images = resources.map((resource) => {
        const { width, height } = resource;
        return {
            id: resource.asset_id,
            title: resource.public_id,
            image: resource.secure_url,
            width,
            height,
        };
    });

    return {
        props: {
            images,
        },
    };
}
