import Head from 'next/head';
import Image from 'next/image';

import { Navbar } from '../components/navbar/navbar.component';
import { Footer } from '../components/footer/footer.component';
import { HeaderBold } from '../components/headerBold/headerBold.component';
import {
    GalleryWrapper,
    GalleryImages,
    GalleryDivider,
} from '../components/galleryStyles/gallery.styles';

import styles from '../styles/Home.module.css';
import styled from 'styled-components';

export default function Home({ images }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Szmatki Kwiatki i Bukiety</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                    lang="pl"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />

            <GalleryWrapper>
                <HeaderBold>Galeria</HeaderBold>
                <GalleryDivider />
                <GalleryImages>
                    {images.map((image) => {
                        return (
                            <div key={image.id}>
                                <Image
                                    width={image.width}
                                    height={image.height}
                                    src={image.image}
                                    alt=""
                                />
                            </div>
                        );
                    })}
                </GalleryImages>
            </GalleryWrapper>
            <Footer />
        </div>
    );
}

export async function getStaticProps() {
    const params = {
        expression: 'folder="sk_gallery"',
    };
    const paramString = Object.keys(params)
        .map((key) => `${key}=${encodeURIComponent(params[key])}`)
        .join('&');

    const results = await fetch(
        `https://api.cloudinary.com/v1_1/${process.env.CLOUDINARY_CLOUD_NAME}/resources/search?${paramString}`,
        {
            headers: {
                Authorization: `Basic ${Buffer.from(
                    process.env.CLOUDINARY_API_KEY +
                        ':' +
                        process.env.CLOUDINARY_API_SECRET
                ).toString('base64')}`,
            },
        }
    ).then((r) => r.json());

    const { resources } = results;
    // console.log(resources);
    const images = resources.map((resource) => {
        const { width, height } = resource;
        return {
            id: resource.asset_id,
            title: resource.public_id,
            image: resource.secure_url,
            width,
            height,
        };
    });

    return {
        props: {
            images,
        },
    };
}
