import Head from 'next/head';

import { Navbar } from '../components/navbar/navbar.component';
import { Hero } from '../components/sections/hero/hero.component';
import { Offer } from '../components/sections/offer/offer.component';
import { About } from '../components/sections/about/about.component';
import { Contact } from '../components/sections/contact/contact.component';
import { Footer } from '../components/footer/footer.component';
import { useWindowSize } from '../hooks/useWindowSize';

export default function Home() {
    const windowSize = useWindowSize();

    return (
        <>
            <Head>
                <title>Szmatki Kwiatki i Bukiety</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                    lang="pl"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Navbar />
                <Hero windowSize={windowSize} />
                <Offer />
                <About />
                <Contact windowSize={windowSize} />
                <Footer />
            </main>
        </>
    );
}
