import Head from "next/head";
import Image from "next/image";

import { Navbar } from '../components/navbar/Navbar.component'
// import { Hero } from '../components/hero/Hero.component';
// import { Offer } from "../components/offer/Offer.component";
// import { About } from "../components/sections/about/About.component";
// import { Contact } from "../components/contact/Contact.component";


export default function Home() {
  return (
    <>
      <Head>
        <title>Szmatki Kwiatki i Bukiety</title>
        <meta name="description" content="Generated by create next app" lang="pl"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <Navbar />
          {/* <Hero /> */}
          {/* <Offer />
          <About />
          <Contact /> */}
      </main>
    </>
  );
}
